env:
  matrix:
    - DIST=lenny
    - DIST=etch
    - DIST=squeeze
    - DIST=wheezy
    - DIST=jessie
    - DIST=stretch

language: c
sudo: required
services:
  - docker

before_install:
   - source <(curl https://raw.githubusercontent.com/madworx/cd-ci-glue/master/src/cd-ci-glue.bash)
   
script:
   - (make DEBIAN_VERSION=${DIST} &&
      is_travis_master_push &&
      dockerhub_push_image venenux/venenux-debianok:${DIST}) || true

jobs:
  include:
    - stage: Publish project description to Docker hub
      env: DIST
      script:
        - is_travis_master_push &&
          dockerhub_set_description venenux/venenux-debianok README.md || true
