env:
  matrix:
    - DIST=lenny
    - DIST=etch
    - DIST=squeeze
    - DIST=wheezy
    - DIST=jessie
    - DIST=stretch

language: c
sudo: required
services:
  - docker

script:
   - (make DEBIAN_VERSION=${DIST} DOCKER_NAME=venenux/debian-${DIST} &&
      is_travis_master_push &&
      dockerhub_push_image venenux/debian-${DIST}) || true

jobs:
  include:
    - stage: Publish project description to Docker hub
      env: DIST
      script:
        - is_travis_master_push &&
          dockerhub_set_description venenux/debian-${DIST}) README.md || true
